# Makefile for Windows
SRCDIR=./src
CC=gcc
INCLUDE = C:\msys64\mingw64\include

CFLAGS = -g -I$(INCLUDE) -c
LDFLAGS = -lmingw32 -lSDL2main -lSDL2_image -lSDL2_ttf -lSDL2 -mwindows -lm

game: main.o keybinds.o
	$(CC) main.o keybinds.o -o game $(LDFLAGS)

main.o: $(SRCDIR)/main.c
	$(CC) $(CFLAGS) $(SRCDIR)/main.c

keybinds.o: $(SRCDIR)/keybinds.c ./include/keybinds.h
	    $(CC) $(CFLAGS) $(SRCDIR)/keybinds.c

clean:
	rm *.exe
	rm *.o
